### ISSUE TITLE
Unable to use a local library

### ISSUE THREAD

**Issue by shadycuz** [jenkinsci/ci.jenkins.io-runner#391]
When using the docker image if I pass in my local lib it fails to load because my library doesn't have a `vars` directory. 

If I add a `vars` directory then it still fails. 

```
== Configuring the Jenkins Pipeline library
===== Adding local Pipeline libs
2021-03-10 08:19:07.021+0000 [id=26]    WARNING i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class jenkins.plugins.git.GitSCMSource#owner: type is abstract but not Describable.
Started
Resume disabled by user, switching to high-performance, low-durability mode.
ERROR: Could not find any definition of libraries [pipeline-library]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: Loading libraries failed

1 error

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
        at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
        at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
        at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
        at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
        at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:571)
        at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:523)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:337)
        at hudson.model.ResourceController.execute(ResourceController.java:97)
        at hudson.model.Executor.run(Executor.java:428)
Finished: FAILURE
```

**Comment by shadycuz** [comment]
I got mine to work like this after several hours of troubleshooting.

```groovy
println("===== Adding local Pipeline libs")

def stdout = new StringBuilder()
def stderr = new StringBuilder()

File script = File.createTempFile("temp",".sh")

def lib = "/var/jenkins_home/lib"

script.write(
    """#!/usr/bin/env bash
    mkdir ${lib} || true
    cp -r /var/jenkins_home/pipeline-library/* ${lib}

    git config --global user.email "shadycuz@gmail.com"
    git config --global user.name "shadycuz"

    cd ${lib}
    rm -rf .git || true
    git init
    git add --all
    git commit -m init
    """
)

def proc = "bash ${script.absolutePath}".execute()

proc.consumeProcessOutput(stdout, stderr)
proc.waitForOrKill(5000)

if (stderr) {
    println("stdout: ${stdout}")
    println("stderr: ${stderr}")
}

def scm = new GitSCMSource("pipeline-library", lib, null, null, null, false)

lc = new LibraryConfiguration("pipeline-library", new SCMSourceRetriever(scm))
lc.with {
    implicit = true
    defaultVersion = "master"
}
```

The nice part about doing it like this is that everytime I make a change to a job or my library I do not have to commit or push anything to test. I can just run:

```
docker run --rm -v /home/shadycuz/repos/dsty/jenkins-std-lib/:/var/jenkins_home/pipeline-library -v $PWD:/workspace iorunner -f /workspace/test-dev
```
